import tensorflow as tf
import numpy as np

from .net_caffee2tf import C2T_Network

class PretrainNetwork(C2T_Network):
    def __init__(self, inputs, weight = None, trainable=True):
        if weight != None:
            self.var = np.load(weight).tolist()
            # for key in self.var.keys():
            #     print(key, self.var[key].keys())
        self.from_scratch = (weight == None)
        super(PretrainNetwork,self).__init__(inputs, trainable)

    def make_var(self, name, shape):
        if self.from_scratch:
            return tf.get_variable(name, shape)
        else:
            scope = tf.get_variable_scope().name.split('/')[-1]
            return tf.get_variable(name, initializer=tf.constant(self.var[scope][name]), trainable = self.trainable)

class VGG_Places365(PretrainNetwork):
    # auto generated by caffe2tensorflow_python3
    # https://github.com/GZHermit/caffe2tensorflow_python3
    def setup(self):
        (self.feed('data')
            .conv(3, 3, 64, 1, 1, name='conv1_1')
            .conv(3, 3, 64, 1, 1, name='conv1_2')
            .max_pool(2, 2, 2, 2, name='pool1')
            .conv(3, 3, 128, 1, 1, name='conv2_1')
            .conv(3, 3, 128, 1, 1, name='conv2_2')
            .max_pool(2, 2, 2, 2, name='pool2')
            .conv(3, 3, 256, 1, 1, name='conv3_1')
            .conv(3, 3, 256, 1, 1, name='conv3_2')
            .conv(3, 3, 256, 1, 1, name='conv3_3')
            .max_pool(2, 2, 2, 2, name='pool3')
            .conv(3, 3, 512, 1, 1, name='conv4_1')
            .conv(3, 3, 512, 1, 1, name='conv4_2')
            .conv(3, 3, 512, 1, 1, name='conv4_3')
            .max_pool(2, 2, 2, 2, name='pool4')
            # .conv(3, 3, 512, 1, 1, name='conv5_1')
            # .conv(3, 3, 512, 1, 1, name='conv5_2')
            # .conv(3, 3, 512, 1, 1, name='conv5_3')
            # .max_pool(2, 2, 2, 2, name='pool5')
            # .fc(4096, name='fc6')
            # .fc(4096, name='fc7')
            # .fc(365, relu=False, name='fc8a')
            # .softmax(name='prob')
        )
        
class Alex_Places365(PretrainNetwork):
    # auto generated by caffe2tensorflow_python3
    # https://github.com/GZHermit/caffe2tensorflow_python3
    def setup(self):
        (self.feed('data')
            .conv(11, 11, 96, 4, 4, padding='VALID', name='conv1')
            .max_pool(3, 3, 2, 2, padding='VALID', name='pool1')
            .lrn(2, 1.9999999494757503e-05, 0.75, name='norm1')
            .conv(5, 5, 256, 1, 1, group=2, name='conv2')
            .max_pool(3, 3, 2, 2, padding='VALID', name='pool2')
            .lrn(2, 1.9999999494757503e-05, 0.75, name='norm2')
            .conv(3, 3, 384, 1, 1, name='conv3')
            .conv(3, 3, 384, 1, 1, group=2, name='conv4')
            .conv(3, 3, 256, 1, 1, group=2, name='conv5')
            .max_pool(3, 3, 2, 2, padding='VALID', name='pool5')
            # .fc(4096, name='fc6')
            # .fc(4096, name='fc7')
            # .fc(365, relu=False, name='fc8')
            # .softmax(name='prob')
        )

class Googlenet_Places365(PretrainNetwork):
    # auto generated by caffe2tensorflow_python3
    # https://github.com/GZHermit/caffe2tensorflow_python3
    def setup(self):
        (self.feed('data')
             .conv(7, 7, 64, 2, 2, name='conv1_7x7_s2')
             .max_pool(3, 3, 2, 2, name='pool1_3x3_s2')
             .lrn(2, 1.9999999494757503e-05, 0.75, name='pool1_norm1')
             .conv(1, 1, 64, 1, 1, name='conv2_3x3_reduce')
             .conv(3, 3, 192, 1, 1, name='conv2_3x3')
             .lrn(2, 1.9999999494757503e-05, 0.75, name='conv2_norm2')
             .max_pool(3, 3, 2, 2, name='pool2_3x3_s2')
             .conv(1, 1, 64, 1, 1, name='inception_3a_1x1'))

        (self.feed('pool2_3x3_s2')
             .conv(1, 1, 96, 1, 1, name='inception_3a_3x3_reduce')
             .conv(3, 3, 128, 1, 1, name='inception_3a_3x3'))

        (self.feed('pool2_3x3_s2')
             .conv(1, 1, 16, 1, 1, name='inception_3a_5x5_reduce')
             .conv(5, 5, 32, 1, 1, name='inception_3a_5x5'))

        (self.feed('pool2_3x3_s2')
             .max_pool(3, 3, 1, 1, name='inception_3a_pool')
             .conv(1, 1, 32, 1, 1, name='inception_3a_pool_proj'))

        (self.feed('inception_3a_1x1', 
                   'inception_3a_3x3', 
                   'inception_3a_5x5', 
                   'inception_3a_pool_proj')
             .concat(3, name='inception_3a_output')
             .conv(1, 1, 128, 1, 1, name='inception_3b_1x1'))

        (self.feed('inception_3a_output')
             .conv(1, 1, 128, 1, 1, name='inception_3b_3x3_reduce')
             .conv(3, 3, 192, 1, 1, name='inception_3b_3x3'))

        (self.feed('inception_3a_output')
             .conv(1, 1, 32, 1, 1, name='inception_3b_5x5_reduce')
             .conv(5, 5, 96, 1, 1, name='inception_3b_5x5'))

        (self.feed('inception_3a_output')
             .max_pool(3, 3, 1, 1, name='inception_3b_pool')
             .conv(1, 1, 64, 1, 1, name='inception_3b_pool_proj'))

        (self.feed('inception_3b_1x1', 
                   'inception_3b_3x3', 
                   'inception_3b_5x5', 
                   'inception_3b_pool_proj')
             .concat(3, name='inception_3b_output')
             .max_pool(3, 3, 2, 2, name='pool3_3x3_s2')
             .conv(1, 1, 192, 1, 1, name='inception_4a_1x1'))

        (self.feed('pool3_3x3_s2')
             .conv(1, 1, 96, 1, 1, name='inception_4a_3x3_reduce')
             .conv(3, 3, 208, 1, 1, name='inception_4a_3x3'))

        (self.feed('pool3_3x3_s2')
             .conv(1, 1, 16, 1, 1, name='inception_4a_5x5_reduce')
             .conv(5, 5, 48, 1, 1, name='inception_4a_5x5'))

        (self.feed('pool3_3x3_s2')
             .max_pool(3, 3, 1, 1, name='inception_4a_pool')
             .conv(1, 1, 64, 1, 1, name='inception_4a_pool_proj'))

        (self.feed('inception_4a_1x1', 
                   'inception_4a_3x3', 
                   'inception_4a_5x5', 
                   'inception_4a_pool_proj')
             .concat(3, name='inception_4a_output')
             .conv(1, 1, 160, 1, 1, name='inception_4b_1x1'))

        (self.feed('inception_4a_output')
             .conv(1, 1, 112, 1, 1, name='inception_4b_3x3_reduce')
             .conv(3, 3, 224, 1, 1, name='inception_4b_3x3'))

        (self.feed('inception_4a_output')
             .conv(1, 1, 24, 1, 1, name='inception_4b_5x5_reduce')
             .conv(5, 5, 64, 1, 1, name='inception_4b_5x5'))

        (self.feed('inception_4a_output')
             .max_pool(3, 3, 1, 1, name='inception_4b_pool')
             .conv(1, 1, 64, 1, 1, name='inception_4b_pool_proj'))

        (self.feed('inception_4b_1x1', 
                   'inception_4b_3x3', 
                   'inception_4b_5x5', 
                   'inception_4b_pool_proj')
             .concat(3, name='inception_4b_output')
             .conv(1, 1, 128, 1, 1, name='inception_4c_1x1'))

        (self.feed('inception_4b_output')
             .conv(1, 1, 128, 1, 1, name='inception_4c_3x3_reduce')
             .conv(3, 3, 256, 1, 1, name='inception_4c_3x3'))

        (self.feed('inception_4b_output')
             .conv(1, 1, 24, 1, 1, name='inception_4c_5x5_reduce')
             .conv(5, 5, 64, 1, 1, name='inception_4c_5x5'))

        (self.feed('inception_4b_output')
             .max_pool(3, 3, 1, 1, name='inception_4c_pool')
             .conv(1, 1, 64, 1, 1, name='inception_4c_pool_proj'))

        (self.feed('inception_4c_1x1', 
                   'inception_4c_3x3', 
                   'inception_4c_5x5', 
                   'inception_4c_pool_proj')
             .concat(3, name='inception_4c_output')
             .conv(1, 1, 112, 1, 1, name='inception_4d_1x1'))

        (self.feed('inception_4c_output')
             .conv(1, 1, 144, 1, 1, name='inception_4d_3x3_reduce')
             .conv(3, 3, 288, 1, 1, name='inception_4d_3x3'))

        (self.feed('inception_4c_output')
             .conv(1, 1, 32, 1, 1, name='inception_4d_5x5_reduce')
             .conv(5, 5, 64, 1, 1, name='inception_4d_5x5'))

        (self.feed('inception_4c_output')
             .max_pool(3, 3, 1, 1, name='inception_4d_pool')
             .conv(1, 1, 64, 1, 1, name='inception_4d_pool_proj'))

        (self.feed('inception_4d_1x1', 
                   'inception_4d_3x3', 
                   'inception_4d_5x5', 
                   'inception_4d_pool_proj')
             .concat(3, name='inception_4d_output')
             .conv(1, 1, 256, 1, 1, name='inception_4e_1x1'))

        (self.feed('inception_4d_output')
             .conv(1, 1, 160, 1, 1, name='inception_4e_3x3_reduce')
             .conv(3, 3, 320, 1, 1, name='inception_4e_3x3'))

        (self.feed('inception_4d_output')
             .conv(1, 1, 32, 1, 1, name='inception_4e_5x5_reduce')
             .conv(5, 5, 128, 1, 1, name='inception_4e_5x5'))

        (self.feed('inception_4d_output')
             .max_pool(3, 3, 1, 1, name='inception_4e_pool')
             .conv(1, 1, 128, 1, 1, name='inception_4e_pool_proj'))

        (self.feed('inception_4e_1x1', 
                   'inception_4e_3x3', 
                   'inception_4e_5x5', 
                   'inception_4e_pool_proj')
             .concat(3, name='inception_4e_output')
             .max_pool(3, 3, 2, 2, name='pool4_3x3_s2')
             .conv(1, 1, 256, 1, 1, name='inception_5a_1x1'))

        (self.feed('pool4_3x3_s2')
             .conv(1, 1, 160, 1, 1, name='inception_5a_3x3_reduce')
             .conv(3, 3, 320, 1, 1, name='inception_5a_3x3'))

        (self.feed('pool4_3x3_s2')
             .conv(1, 1, 32, 1, 1, name='inception_5a_5x5_reduce')
             .conv(5, 5, 128, 1, 1, name='inception_5a_5x5'))

        (self.feed('pool4_3x3_s2')
             .max_pool(3, 3, 1, 1, name='inception_5a_pool')
             .conv(1, 1, 128, 1, 1, name='inception_5a_pool_proj'))

        (self.feed('inception_5a_1x1', 
                   'inception_5a_3x3', 
                   'inception_5a_5x5', 
                   'inception_5a_pool_proj')
             .concat(3, name='inception_5a_output')
             .conv(1, 1, 384, 1, 1, name='inception_5b_1x1'))

        (self.feed('inception_5a_output')
             .conv(1, 1, 192, 1, 1, name='inception_5b_3x3_reduce')
             .conv(3, 3, 384, 1, 1, name='inception_5b_3x3'))

        (self.feed('inception_5a_output')
             .conv(1, 1, 48, 1, 1, name='inception_5b_5x5_reduce')
             .conv(5, 5, 128, 1, 1, name='inception_5b_5x5'))

        (self.feed('inception_5a_output')
             .max_pool(3, 3, 1, 1, name='inception_5b_pool')
             .conv(1, 1, 128, 1, 1, name='inception_5b_pool_proj'))

        # (self.feed('inception_5b_1x1', 
        #            'inception_5b_3x3', 
        #            'inception_5b_5x5', 
        #            'inception_5b_pool_proj')
        #      .concat(3, name='inception_5b_output')
        #      .avg_pool(7, 7, 1, 1, padding='VALID', name='pool5_7x7_s1')
        #      .fc(365, relu=False, name='loss3_classifier')
        #      .softmax(name='prob'))

class Res152_Places365(PretrainNetwork):
    # auto generated by caffe2tensorflow_python3
    # https://github.com/GZHermit/caffe2tensorflow_python3
    def setup(self):
        (self.feed('data')
             .conv(7, 7, 64, 2, 2, biased=False, relu=False, name='conv1')
             .batch_normalization(relu=True, name='bn_conv1')
             .max_pool(3, 3, 2, 2, name='pool1')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res2a_branch1')
             .batch_normalization(name='bn2a_branch1'))

        (self.feed('pool1')
             .conv(1, 1, 64, 1, 1, biased=False, relu=False, name='res2a_branch2a')
             .batch_normalization(relu=True, name='bn2a_branch2a')
             .conv(3, 3, 64, 1, 1, biased=False, relu=False, name='res2a_branch2b')
             .batch_normalization(relu=True, name='bn2a_branch2b')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res2a_branch2c')
             .batch_normalization(name='bn2a_branch2c'))

        (self.feed('bn2a_branch1', 
                   'bn2a_branch2c')
             .add(name='res2a')
             .relu(name='res2a_relu')
             .conv(1, 1, 64, 1, 1, biased=False, relu=False, name='res2b_branch2a')
             .batch_normalization(relu=True, name='bn2b_branch2a')
             .conv(3, 3, 64, 1, 1, biased=False, relu=False, name='res2b_branch2b')
             .batch_normalization(relu=True, name='bn2b_branch2b')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res2b_branch2c')
             .batch_normalization(name='bn2b_branch2c'))

        (self.feed('res2a_relu', 
                   'bn2b_branch2c')
             .add(name='res2b')
             .relu(name='res2b_relu')
             .conv(1, 1, 64, 1, 1, biased=False, relu=False, name='res2c_branch2a')
             .batch_normalization(relu=True, name='bn2c_branch2a')
             .conv(3, 3, 64, 1, 1, biased=False, relu=False, name='res2c_branch2b')
             .batch_normalization(relu=True, name='bn2c_branch2b')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res2c_branch2c')
             .batch_normalization(name='bn2c_branch2c'))

        (self.feed('res2b_relu', 
                   'bn2c_branch2c')
             .add(name='res2c')
             .relu(name='res2c_relu')
             .conv(1, 1, 512, 2, 2, biased=False, relu=False, name='res3a_branch1')
             .batch_normalization(name='bn3a_branch1'))

        (self.feed('res2c_relu')
             .conv(1, 1, 128, 2, 2, biased=False, relu=False, name='res3a_branch2a')
             .batch_normalization(relu=True, name='bn3a_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3a_branch2b')
             .batch_normalization(relu=True, name='bn3a_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3a_branch2c')
             .batch_normalization(name='bn3a_branch2c'))

        (self.feed('bn3a_branch1', 
                   'bn3a_branch2c')
             .add(name='res3a')
             .relu(name='res3a_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b1_branch2a')
             .batch_normalization(relu=True, name='bn3b1_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b1_branch2b')
             .batch_normalization(relu=True, name='bn3b1_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b1_branch2c')
             .batch_normalization(name='bn3b1_branch2c'))

        (self.feed('res3a_relu', 
                   'bn3b1_branch2c')
             .add(name='res3b1')
             .relu(name='res3b1_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b2_branch2a')
             .batch_normalization(relu=True, name='bn3b2_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b2_branch2b')
             .batch_normalization(relu=True, name='bn3b2_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b2_branch2c')
             .batch_normalization(name='bn3b2_branch2c'))

        (self.feed('res3b1_relu', 
                   'bn3b2_branch2c')
             .add(name='res3b2')
             .relu(name='res3b2_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b3_branch2a')
             .batch_normalization(relu=True, name='bn3b3_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b3_branch2b')
             .batch_normalization(relu=True, name='bn3b3_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b3_branch2c')
             .batch_normalization(name='bn3b3_branch2c'))

        (self.feed('res3b2_relu', 
                   'bn3b3_branch2c')
             .add(name='res3b3')
             .relu(name='res3b3_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b4_branch2a')
             .batch_normalization(relu=True, name='bn3b4_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b4_branch2b')
             .batch_normalization(relu=True, name='bn3b4_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b4_branch2c')
             .batch_normalization(name='bn3b4_branch2c'))

        (self.feed('res3b3_relu', 
                   'bn3b4_branch2c')
             .add(name='res3b4')
             .relu(name='res3b4_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b5_branch2a')
             .batch_normalization(relu=True, name='bn3b5_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b5_branch2b')
             .batch_normalization(relu=True, name='bn3b5_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b5_branch2c')
             .batch_normalization(name='bn3b5_branch2c'))

        (self.feed('res3b4_relu', 
                   'bn3b5_branch2c')
             .add(name='res3b5')
             .relu(name='res3b5_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b6_branch2a')
             .batch_normalization(relu=True, name='bn3b6_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b6_branch2b')
             .batch_normalization(relu=True, name='bn3b6_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b6_branch2c')
             .batch_normalization(name='bn3b6_branch2c'))

        (self.feed('res3b5_relu', 
                   'bn3b6_branch2c')
             .add(name='res3b6')
             .relu(name='res3b6_relu')
             .conv(1, 1, 128, 1, 1, biased=False, relu=False, name='res3b7_branch2a')
             .batch_normalization(relu=True, name='bn3b7_branch2a')
             .conv(3, 3, 128, 1, 1, biased=False, relu=False, name='res3b7_branch2b')
             .batch_normalization(relu=True, name='bn3b7_branch2b')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res3b7_branch2c')
             .batch_normalization(name='bn3b7_branch2c'))

        (self.feed('res3b6_relu', 
                   'bn3b7_branch2c')
             .add(name='res3b7')
             .relu(name='res3b7_relu')
             .conv(1, 1, 1024, 2, 2, biased=False, relu=False, name='res4a_branch1')
             .batch_normalization(name='bn4a_branch1'))

        (self.feed('res3b7_relu')
             .conv(1, 1, 256, 2, 2, biased=False, relu=False, name='res4a_branch2a')
             .batch_normalization(relu=True, name='bn4a_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4a_branch2b')
             .batch_normalization(relu=True, name='bn4a_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4a_branch2c')
             .batch_normalization(name='bn4a_branch2c'))

        (self.feed('bn4a_branch1', 
                   'bn4a_branch2c')
             .add(name='res4a')
             .relu(name='res4a_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b1_branch2a')
             .batch_normalization(relu=True, name='bn4b1_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b1_branch2b')
             .batch_normalization(relu=True, name='bn4b1_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b1_branch2c')
             .batch_normalization(name='bn4b1_branch2c'))

        (self.feed('res4a_relu', 
                   'bn4b1_branch2c')
             .add(name='res4b1')
             .relu(name='res4b1_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b2_branch2a')
             .batch_normalization(relu=True, name='bn4b2_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b2_branch2b')
             .batch_normalization(relu=True, name='bn4b2_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b2_branch2c')
             .batch_normalization(name='bn4b2_branch2c'))

        (self.feed('res4b1_relu', 
                   'bn4b2_branch2c')
             .add(name='res4b2')
             .relu(name='res4b2_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b3_branch2a')
             .batch_normalization(relu=True, name='bn4b3_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b3_branch2b')
             .batch_normalization(relu=True, name='bn4b3_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b3_branch2c')
             .batch_normalization(name='bn4b3_branch2c'))

        (self.feed('res4b2_relu', 
                   'bn4b3_branch2c')
             .add(name='res4b3')
             .relu(name='res4b3_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b4_branch2a')
             .batch_normalization(relu=True, name='bn4b4_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b4_branch2b')
             .batch_normalization(relu=True, name='bn4b4_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b4_branch2c')
             .batch_normalization(name='bn4b4_branch2c'))

        (self.feed('res4b3_relu', 
                   'bn4b4_branch2c')
             .add(name='res4b4')
             .relu(name='res4b4_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b5_branch2a')
             .batch_normalization(relu=True, name='bn4b5_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b5_branch2b')
             .batch_normalization(relu=True, name='bn4b5_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b5_branch2c')
             .batch_normalization(name='bn4b5_branch2c'))

        (self.feed('res4b4_relu', 
                   'bn4b5_branch2c')
             .add(name='res4b5')
             .relu(name='res4b5_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b6_branch2a')
             .batch_normalization(relu=True, name='bn4b6_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b6_branch2b')
             .batch_normalization(relu=True, name='bn4b6_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b6_branch2c')
             .batch_normalization(name='bn4b6_branch2c'))

        (self.feed('res4b5_relu', 
                   'bn4b6_branch2c')
             .add(name='res4b6')
             .relu(name='res4b6_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b7_branch2a')
             .batch_normalization(relu=True, name='bn4b7_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b7_branch2b')
             .batch_normalization(relu=True, name='bn4b7_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b7_branch2c')
             .batch_normalization(name='bn4b7_branch2c'))

        (self.feed('res4b6_relu', 
                   'bn4b7_branch2c')
             .add(name='res4b7')
             .relu(name='res4b7_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b8_branch2a')
             .batch_normalization(relu=True, name='bn4b8_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b8_branch2b')
             .batch_normalization(relu=True, name='bn4b8_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b8_branch2c')
             .batch_normalization(name='bn4b8_branch2c'))

        (self.feed('res4b7_relu', 
                   'bn4b8_branch2c')
             .add(name='res4b8')
             .relu(name='res4b8_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b9_branch2a')
             .batch_normalization(relu=True, name='bn4b9_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b9_branch2b')
             .batch_normalization(relu=True, name='bn4b9_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b9_branch2c')
             .batch_normalization(name='bn4b9_branch2c'))

        (self.feed('res4b8_relu', 
                   'bn4b9_branch2c')
             .add(name='res4b9')
             .relu(name='res4b9_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b10_branch2a')
             .batch_normalization(relu=True, name='bn4b10_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b10_branch2b')
             .batch_normalization(relu=True, name='bn4b10_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b10_branch2c')
             .batch_normalization(name='bn4b10_branch2c'))

        (self.feed('res4b9_relu', 
                   'bn4b10_branch2c')
             .add(name='res4b10')
             .relu(name='res4b10_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b11_branch2a')
             .batch_normalization(relu=True, name='bn4b11_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b11_branch2b')
             .batch_normalization(relu=True, name='bn4b11_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b11_branch2c')
             .batch_normalization(name='bn4b11_branch2c'))

        (self.feed('res4b10_relu', 
                   'bn4b11_branch2c')
             .add(name='res4b11')
             .relu(name='res4b11_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b12_branch2a')
             .batch_normalization(relu=True, name='bn4b12_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b12_branch2b')
             .batch_normalization(relu=True, name='bn4b12_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b12_branch2c')
             .batch_normalization(name='bn4b12_branch2c'))

        (self.feed('res4b11_relu', 
                   'bn4b12_branch2c')
             .add(name='res4b12')
             .relu(name='res4b12_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b13_branch2a')
             .batch_normalization(relu=True, name='bn4b13_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b13_branch2b')
             .batch_normalization(relu=True, name='bn4b13_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b13_branch2c')
             .batch_normalization(name='bn4b13_branch2c'))

        (self.feed('res4b12_relu', 
                   'bn4b13_branch2c')
             .add(name='res4b13')
             .relu(name='res4b13_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b14_branch2a')
             .batch_normalization(relu=True, name='bn4b14_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b14_branch2b')
             .batch_normalization(relu=True, name='bn4b14_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b14_branch2c')
             .batch_normalization(name='bn4b14_branch2c'))

        (self.feed('res4b13_relu', 
                   'bn4b14_branch2c')
             .add(name='res4b14')
             .relu(name='res4b14_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b15_branch2a')
             .batch_normalization(relu=True, name='bn4b15_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b15_branch2b')
             .batch_normalization(relu=True, name='bn4b15_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b15_branch2c')
             .batch_normalization(name='bn4b15_branch2c'))

        (self.feed('res4b14_relu', 
                   'bn4b15_branch2c')
             .add(name='res4b15')
             .relu(name='res4b15_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b16_branch2a')
             .batch_normalization(relu=True, name='bn4b16_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b16_branch2b')
             .batch_normalization(relu=True, name='bn4b16_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b16_branch2c')
             .batch_normalization(name='bn4b16_branch2c'))

        (self.feed('res4b15_relu', 
                   'bn4b16_branch2c')
             .add(name='res4b16')
             .relu(name='res4b16_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b17_branch2a')
             .batch_normalization(relu=True, name='bn4b17_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b17_branch2b')
             .batch_normalization(relu=True, name='bn4b17_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b17_branch2c')
             .batch_normalization(name='bn4b17_branch2c'))

        (self.feed('res4b16_relu', 
                   'bn4b17_branch2c')
             .add(name='res4b17')
             .relu(name='res4b17_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b18_branch2a')
             .batch_normalization(relu=True, name='bn4b18_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b18_branch2b')
             .batch_normalization(relu=True, name='bn4b18_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b18_branch2c')
             .batch_normalization(name='bn4b18_branch2c'))

        (self.feed('res4b17_relu', 
                   'bn4b18_branch2c')
             .add(name='res4b18')
             .relu(name='res4b18_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b19_branch2a')
             .batch_normalization(relu=True, name='bn4b19_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b19_branch2b')
             .batch_normalization(relu=True, name='bn4b19_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b19_branch2c')
             .batch_normalization(name='bn4b19_branch2c'))

        (self.feed('res4b18_relu', 
                   'bn4b19_branch2c')
             .add(name='res4b19')
             .relu(name='res4b19_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b20_branch2a')
             .batch_normalization(relu=True, name='bn4b20_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b20_branch2b')
             .batch_normalization(relu=True, name='bn4b20_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b20_branch2c')
             .batch_normalization(name='bn4b20_branch2c'))

        (self.feed('res4b19_relu', 
                   'bn4b20_branch2c')
             .add(name='res4b20')
             .relu(name='res4b20_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b21_branch2a')
             .batch_normalization(relu=True, name='bn4b21_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b21_branch2b')
             .batch_normalization(relu=True, name='bn4b21_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b21_branch2c')
             .batch_normalization(name='bn4b21_branch2c'))

        (self.feed('res4b20_relu', 
                   'bn4b21_branch2c')
             .add(name='res4b21')
             .relu(name='res4b21_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b22_branch2a')
             .batch_normalization(relu=True, name='bn4b22_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b22_branch2b')
             .batch_normalization(relu=True, name='bn4b22_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b22_branch2c')
             .batch_normalization(name='bn4b22_branch2c'))

        (self.feed('res4b21_relu', 
                   'bn4b22_branch2c')
             .add(name='res4b22')
             .relu(name='res4b22_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b23_branch2a')
             .batch_normalization(relu=True, name='bn4b23_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b23_branch2b')
             .batch_normalization(relu=True, name='bn4b23_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b23_branch2c')
             .batch_normalization(name='bn4b23_branch2c'))

        (self.feed('res4b22_relu', 
                   'bn4b23_branch2c')
             .add(name='res4b23')
             .relu(name='res4b23_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b24_branch2a')
             .batch_normalization(relu=True, name='bn4b24_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b24_branch2b')
             .batch_normalization(relu=True, name='bn4b24_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b24_branch2c')
             .batch_normalization(name='bn4b24_branch2c'))

        (self.feed('res4b23_relu', 
                   'bn4b24_branch2c')
             .add(name='res4b24')
             .relu(name='res4b24_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b25_branch2a')
             .batch_normalization(relu=True, name='bn4b25_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b25_branch2b')
             .batch_normalization(relu=True, name='bn4b25_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b25_branch2c')
             .batch_normalization(name='bn4b25_branch2c'))

        (self.feed('res4b24_relu', 
                   'bn4b25_branch2c')
             .add(name='res4b25')
             .relu(name='res4b25_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b26_branch2a')
             .batch_normalization(relu=True, name='bn4b26_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b26_branch2b')
             .batch_normalization(relu=True, name='bn4b26_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b26_branch2c')
             .batch_normalization(name='bn4b26_branch2c'))

        (self.feed('res4b25_relu', 
                   'bn4b26_branch2c')
             .add(name='res4b26')
             .relu(name='res4b26_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b27_branch2a')
             .batch_normalization(relu=True, name='bn4b27_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b27_branch2b')
             .batch_normalization(relu=True, name='bn4b27_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b27_branch2c')
             .batch_normalization(name='bn4b27_branch2c'))

        (self.feed('res4b26_relu', 
                   'bn4b27_branch2c')
             .add(name='res4b27')
             .relu(name='res4b27_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b28_branch2a')
             .batch_normalization(relu=True, name='bn4b28_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b28_branch2b')
             .batch_normalization(relu=True, name='bn4b28_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b28_branch2c')
             .batch_normalization(name='bn4b28_branch2c'))

        (self.feed('res4b27_relu', 
                   'bn4b28_branch2c')
             .add(name='res4b28')
             .relu(name='res4b28_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b29_branch2a')
             .batch_normalization(relu=True, name='bn4b29_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b29_branch2b')
             .batch_normalization(relu=True, name='bn4b29_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b29_branch2c')
             .batch_normalization(name='bn4b29_branch2c'))

        (self.feed('res4b28_relu', 
                   'bn4b29_branch2c')
             .add(name='res4b29')
             .relu(name='res4b29_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b30_branch2a')
             .batch_normalization(relu=True, name='bn4b30_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b30_branch2b')
             .batch_normalization(relu=True, name='bn4b30_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b30_branch2c')
             .batch_normalization(name='bn4b30_branch2c'))

        (self.feed('res4b29_relu', 
                   'bn4b30_branch2c')
             .add(name='res4b30')
             .relu(name='res4b30_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b31_branch2a')
             .batch_normalization(relu=True, name='bn4b31_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b31_branch2b')
             .batch_normalization(relu=True, name='bn4b31_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b31_branch2c')
             .batch_normalization(name='bn4b31_branch2c'))

        (self.feed('res4b30_relu', 
                   'bn4b31_branch2c')
             .add(name='res4b31')
             .relu(name='res4b31_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b32_branch2a')
             .batch_normalization(relu=True, name='bn4b32_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b32_branch2b')
             .batch_normalization(relu=True, name='bn4b32_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b32_branch2c')
             .batch_normalization(name='bn4b32_branch2c'))

        (self.feed('res4b31_relu', 
                   'bn4b32_branch2c')
             .add(name='res4b32')
             .relu(name='res4b32_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b33_branch2a')
             .batch_normalization(relu=True, name='bn4b33_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b33_branch2b')
             .batch_normalization(relu=True, name='bn4b33_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b33_branch2c')
             .batch_normalization(name='bn4b33_branch2c'))

        (self.feed('res4b32_relu', 
                   'bn4b33_branch2c')
             .add(name='res4b33')
             .relu(name='res4b33_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b34_branch2a')
             .batch_normalization(relu=True, name='bn4b34_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b34_branch2b')
             .batch_normalization(relu=True, name='bn4b34_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b34_branch2c')
             .batch_normalization(name='bn4b34_branch2c'))

        (self.feed('res4b33_relu', 
                   'bn4b34_branch2c')
             .add(name='res4b34')
             .relu(name='res4b34_relu')
             .conv(1, 1, 256, 1, 1, biased=False, relu=False, name='res4b35_branch2a')
             .batch_normalization(relu=True, name='bn4b35_branch2a')
             .conv(3, 3, 256, 1, 1, biased=False, relu=False, name='res4b35_branch2b')
             .batch_normalization(relu=True, name='bn4b35_branch2b')
             .conv(1, 1, 1024, 1, 1, biased=False, relu=False, name='res4b35_branch2c')
             .batch_normalization(name='bn4b35_branch2c'))

        (self.feed('res4b34_relu', 
                   'bn4b35_branch2c')
             .add(name='res4b35')
             .relu(name='res4b35_relu')
             .conv(1, 1, 2048, 2, 2, biased=False, relu=False, name='res5a_branch1')
             .batch_normalization(name='bn5a_branch1'))

        (self.feed('res4b35_relu')
             .conv(1, 1, 512, 2, 2, biased=False, relu=False, name='res5a_branch2a')
             .batch_normalization(relu=True, name='bn5a_branch2a')
             .conv(3, 3, 512, 1, 1, biased=False, relu=False, name='res5a_branch2b')
             .batch_normalization(relu=True, name='bn5a_branch2b')
             .conv(1, 1, 2048, 1, 1, biased=False, relu=False, name='res5a_branch2c')
             .batch_normalization(name='bn5a_branch2c'))

        (self.feed('bn5a_branch1', 
                   'bn5a_branch2c')
             .add(name='res5a')
             .relu(name='res5a_relu')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res5b_branch2a')
             .batch_normalization(relu=True, name='bn5b_branch2a')
             .conv(3, 3, 512, 1, 1, biased=False, relu=False, name='res5b_branch2b')
             .batch_normalization(relu=True, name='bn5b_branch2b')
             .conv(1, 1, 2048, 1, 1, biased=False, relu=False, name='res5b_branch2c')
             .batch_normalization(name='bn5b_branch2c'))

        (self.feed('res5a_relu', 
                   'bn5b_branch2c')
             .add(name='res5b')
             .relu(name='res5b_relu')
             .conv(1, 1, 512, 1, 1, biased=False, relu=False, name='res5c_branch2a')
             .batch_normalization(relu=True, name='bn5c_branch2a')
             .conv(3, 3, 512, 1, 1, biased=False, relu=False, name='res5c_branch2b')
             .batch_normalization(relu=True, name='bn5c_branch2b')
             .conv(1, 1, 2048, 1, 1, biased=False, relu=False, name='res5c_branch2c')
             .batch_normalization(name='bn5c_branch2c'))

        # (self.feed('res5b_relu', 
        #            'bn5c_branch2c')
        #      .add(name='res5c')
        #      .relu(name='res5c_relu')
        #      .avg_pool(7, 7, 1, 1, padding='VALID', name='pool5')
        #      .fc(1365, relu=False, name='fc1365')
        #      .softmax(name='prob'))